GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTg1MDEwMiwiZXhwIjoxNjg5ODUwMTE3fQ.wGuljBIMJSBD-2O7GstV8qSQPqIA7-_npQ95Ict05d4

###

POST http://localhost:5000/api/auth/token
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTg1MDA4NX0.7Lag6K1HxJEzWKDispZY72HnqLWOM0YdTZNtx-v34cA"
}

###

POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email": "tqwe123",
    "password": "test"
}

###

POST http://localhost:5000/api/auth/logout
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY4OTg1MDEwMiwiZXhwIjoxNjg5ODUwMTE3fQ.wGuljBIMJSBD-2O7GstV8qSQPqIA7-_npQ95Ict05d4"
}

###

POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "name": "securepass",
    "email": "te@st.test",
    "password": "zaq1@WSX"
}
